application: de-bee
version: 1
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets
  
- url: /images
  static_dir: images
  
- url: /scripts
  static_dir: scripts
  
- url: /who.*
  script: who.py
  login: admin
  
- url: /what.*
  script: what.py
  login: admin
  
- url: /transactions.*
  script: transactions.py
  login: admin
  
- url: .*
  script: main.py
